
[package]
name = "mungos"
description = "MongoDB in rust, simplified."
version = "0.5.6"
edition = "2021"
authors = ["MoghTech"]
repository = "https://github.com/mbecker20/mungos"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.202"
serde_derive = "1.0.203"
mongodb = "3.0.0"
envy = "0.4.2"
anyhow = "1.0.86"
futures = "0.3.30"