[package]
name = "mungos"
version = "0.3.18"
edition = "2021"
authors = ["MoghTech"]
description = "MongoDB in rust, simplified."
repository = "https://github.com/mbecker20/mungos"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { version = "2.4", features = ["zstd-compression", "zlib-compression", "snappy-compression"] }
tokio = "1.26"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.3"
futures-util = "0.3"
anyhow = "1.0"
envy = "0.4"