[workspace]
members = ["derive"]

[workspace.package]
version = "0.4.5"
edition = "2021"
authors = ["MoghTech"]
repository = "https://github.com/mbecker20/mungos"
license = "MIT"

[package]
name = "mungos"
description = "MongoDB in rust, simplified."
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.mongodb]
version = "2.5"
features = ["zstd-compression", "zlib-compression", "snappy-compression"]

[dependencies]
mungos_derive = "0.4.4"
tokio = "1.28"
serde = "1.0"
futures = "0.3"
anyhow = "1.0"
envy = "0.4"
async-trait = "0.1"