[package]
name = "meerkat"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.0.0"
serde = "1.0.130"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.3"