[package]
name = "mungos"
version = "0.2.9"
edition = "2021"
authors = ["MoghTech"]
description = "MongoDB in rust, simplified."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { version = "2.2.2", features = ["zstd-compression", "zlib-compression", "snappy-compression"] }
serde = "1.0.130"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.3"