
[package]
name = "mungos"
description = "MongoDB in rust, simplified."
version = "0.5.4"
edition = "2021"
authors = ["MoghTech"]
repository = "https://github.com/mbecker20/mungos"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.mongodb]
version = "2.8.0"
features = ["zstd-compression", "zlib-compression", "snappy-compression"]

[dependencies.serde]
version = "1.0.193"
features = ["derive"]

[dependencies]
async-trait = "0.1.75"
envy = "0.4.2"
anyhow = "1.0.77"
futures = "0.3.30"
# tokio = "1.3"
# tokio-util = "0.7"